### ISSUE TITLE
3 files with a 404 status

### ISSUE THREAD

**Issue by n-o-t** [monkeymademe/piritos#2]
Project running on a raspberry pi shows 3 files with a 404 status
/static/style.90c21883.css 
/static/main.b083225b.js 
/static/images/RitosBingoWeb1200.31b17ebb.png

**Comment by monkeymademe** [comment]
Sorry I missed them on the last commit they are up now thanks for letting me know

**Comment by n-o-t** [comment]
No worries, thank you for the fix and thanks a lot for this project!
